version: '3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kittygram_user -d kittygram"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ayzaoyun/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ayzaoyun/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: ayzaoyun/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/usr/share/nginx/html/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media: 